package com.penglecode.xmodule.usercenter.model;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 学校
 * 
 * @author Mybatis-Generator
 * @date	2021年01月09日 下午 14:23:47
 */
@Model(name="学校信息", alias="School")
public class School implements BaseModel<School> {
     
    private static final long serialVersionUID = 1L;

    /** id */
    @Id
    private Long id;

    /** 区uuid */
    private String areaUuid;

    /** uuid */
    private String uuid;

    /** 名称 */
    private String name;

    /** 状态 : 0:无效
1:有效 */
    private Integer status;

    /** 创建时间 */
    private String createdTime;

    /** 更新时间 */
    private String modifiedTime;

    /** 类型
1:一般学校
2:培训学校 */
    private Integer type;

    /** car_flag */
    private Integer carFlag;

    /** 0未开通网课 1开通网课 */
    private String yunkeFlag;

    /** 网课编号 */
    private String yunkeCode;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAreaUuid() {
        return areaUuid;
    }

    public void setAreaUuid(String areaUuid) {
        this.areaUuid = areaUuid;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getModifiedTime() {
        return modifiedTime;
    }

    public void setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getCarFlag() {
        return carFlag;
    }

    public void setCarFlag(Integer carFlag) {
        this.carFlag = carFlag;
    }

    public String getYunkeFlag() {
        return yunkeFlag;
    }

    public void setYunkeFlag(String yunkeFlag) {
        this.yunkeFlag = yunkeFlag;
    }

    public String getYunkeCode() {
        return yunkeCode;
    }

    public void setYunkeCode(String yunkeCode) {
        this.yunkeCode = yunkeCode;
    }

    public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            super();
        }

        public MapBuilder withId(Long ... id) {
            modelProperties.put("id", BaseModel.first(id, getId()));
            return this;
        }

        public MapBuilder withAreaUuid(String ... areaUuid) {
            modelProperties.put("areaUuid", BaseModel.first(areaUuid, getAreaUuid()));
            return this;
        }

        public MapBuilder withUuid(String ... uuid) {
            modelProperties.put("uuid", BaseModel.first(uuid, getUuid()));
            return this;
        }

        public MapBuilder withName(String ... name) {
            modelProperties.put("name", BaseModel.first(name, getName()));
            return this;
        }

        public MapBuilder withStatus(Integer ... status) {
            modelProperties.put("status", BaseModel.first(status, getStatus()));
            return this;
        }

        public MapBuilder withCreatedTime(String ... createdTime) {
            modelProperties.put("createdTime", BaseModel.first(createdTime, getCreatedTime()));
            return this;
        }

        public MapBuilder withModifiedTime(String ... modifiedTime) {
            modelProperties.put("modifiedTime", BaseModel.first(modifiedTime, getModifiedTime()));
            return this;
        }

        public MapBuilder withType(Integer ... type) {
            modelProperties.put("type", BaseModel.first(type, getType()));
            return this;
        }

        public MapBuilder withCarFlag(Integer ... carFlag) {
            modelProperties.put("carFlag", BaseModel.first(carFlag, getCarFlag()));
            return this;
        }

        public MapBuilder withYunkeFlag(String ... yunkeFlag) {
            modelProperties.put("yunkeFlag", BaseModel.first(yunkeFlag, getYunkeFlag()));
            return this;
        }

        public MapBuilder withYunkeCode(String ... yunkeCode) {
            modelProperties.put("yunkeCode", BaseModel.first(yunkeCode, getYunkeCode()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}