package com.penglecode.xmodule.usercenter.model;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 角色表
 * 
 * @author Customized-Mybatis-Generator
 * @date	2021年01月09日 下午 23:54:03
 */
@Model(name="系统角色", alias="SysRole")
public class SysRole implements BaseModel<SysRole> {
     
    private static final long serialVersionUID = 1L;

    /** 编号 */
    @Id
    private String id;

    /** 归属机构 */
    private String officeId;

    /** 角色名称 */
    private String name;

    /** 英文名称 */
    private String enname;

    /** 角色类型 */
    private String roleType;

    /** 数据范围 */
    private String dataScope;

    /** 是否系统数据 */
    private String isSys;

    /** 是否可用 */
    private String useable;

    /** 创建者 */
    private String createBy;

    /** 创建时间 */
    private String createDate;

    /** 更新者 */
    private String updateBy;

    /** 更新时间 */
    private String updateDate;

    /** 备注信息 */
    private String remarks;

    /** 删除标记 */
    private String delFlag;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOfficeId() {
        return officeId;
    }

    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEnname() {
        return enname;
    }

    public void setEnname(String enname) {
        this.enname = enname;
    }

    public String getRoleType() {
        return roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    public String getDataScope() {
        return dataScope;
    }

    public void setDataScope(String dataScope) {
        this.dataScope = dataScope;
    }

    public String getIsSys() {
        return isSys;
    }

    public void setIsSys(String isSys) {
        this.isSys = isSys;
    }

    public String getUseable() {
        return useable;
    }

    public void setUseable(String useable) {
        this.useable = useable;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<>();

        MapBuilder() {
            super();
        }

        public MapBuilder withId(String ... id) {
            modelProperties.put("id", BaseModel.first(id, getId()));
            return this;
        }

        public MapBuilder withOfficeId(String ... officeId) {
            modelProperties.put("officeId", BaseModel.first(officeId, getOfficeId()));
            return this;
        }

        public MapBuilder withName(String ... name) {
            modelProperties.put("name", BaseModel.first(name, getName()));
            return this;
        }

        public MapBuilder withEnname(String ... enname) {
            modelProperties.put("enname", BaseModel.first(enname, getEnname()));
            return this;
        }

        public MapBuilder withRoleType(String ... roleType) {
            modelProperties.put("roleType", BaseModel.first(roleType, getRoleType()));
            return this;
        }

        public MapBuilder withDataScope(String ... dataScope) {
            modelProperties.put("dataScope", BaseModel.first(dataScope, getDataScope()));
            return this;
        }

        public MapBuilder withIsSys(String ... isSys) {
            modelProperties.put("isSys", BaseModel.first(isSys, getIsSys()));
            return this;
        }

        public MapBuilder withUseable(String ... useable) {
            modelProperties.put("useable", BaseModel.first(useable, getUseable()));
            return this;
        }

        public MapBuilder withCreateBy(String ... createBy) {
            modelProperties.put("createBy", BaseModel.first(createBy, getCreateBy()));
            return this;
        }

        public MapBuilder withCreateDate(String ... createDate) {
            modelProperties.put("createDate", BaseModel.first(createDate, getCreateDate()));
            return this;
        }

        public MapBuilder withUpdateBy(String ... updateBy) {
            modelProperties.put("updateBy", BaseModel.first(updateBy, getUpdateBy()));
            return this;
        }

        public MapBuilder withUpdateDate(String ... updateDate) {
            modelProperties.put("updateDate", BaseModel.first(updateDate, getUpdateDate()));
            return this;
        }

        public MapBuilder withRemarks(String ... remarks) {
            modelProperties.put("remarks", BaseModel.first(remarks, getRemarks()));
            return this;
        }

        public MapBuilder withDelFlag(String ... delFlag) {
            modelProperties.put("delFlag", BaseModel.first(delFlag, getDelFlag()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}