package com.penglecode.xmodule.platform.upms.model;

import java.util.LinkedHashMap;
import java.util.Map;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;

/**
 * UPMS组织机构 (upms_organization) 实体类
 * 
 * @author Mybatis-Generator
 * @date	2020年03月11日 上午 11:33:57
 */
@Model(name="UPMS组织机构", alias="Organization")
public class UpmsOrganization implements BaseModel<UpmsOrganization> {
     
    private static final long serialVersionUID = 1L;

    /** 组织ID */
    @Id
    private Long orgId;

    /** 机构代码 */
    private String orgCode;

    /** 组织名称 */
    private String orgName;

    /** 组织描述 */
    private String orgDesc;

    /** 创建时间 */
    private String createTime;

    /** 创建者用户ID */
    private Long createBy;

    /** 更新时间 */
    private String updateTime;

    /** 更新者用户ID */
    private Long updateBy;
    
    //以下属于辅助字段
    
    private Long userId;

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgDesc() {
        return orgDesc;
    }

    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Long getCreateBy() {
        return createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public Long getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            
        }

        public MapBuilder withOrgId(Long ... orgId) {
            modelProperties.put("orgId", BaseModel.first(orgId, getOrgId()));
            return this;
        }

        public MapBuilder withOrgCode(String ... orgCode) {
            modelProperties.put("orgCode", BaseModel.first(orgCode, getOrgCode()));
            return this;
        }

        public MapBuilder withOrgName(String ... orgName) {
            modelProperties.put("orgName", BaseModel.first(orgName, getOrgName()));
            return this;
        }

        public MapBuilder withOrgDesc(String ... orgDesc) {
            modelProperties.put("orgDesc", BaseModel.first(orgDesc, getOrgDesc()));
            return this;
        }

        public MapBuilder withCreateTime(String ... createTime) {
            modelProperties.put("createTime", BaseModel.first(createTime, getCreateTime()));
            return this;
        }

        public MapBuilder withCreateBy(Long ... createBy) {
            modelProperties.put("createBy", BaseModel.first(createBy, getCreateBy()));
            return this;
        }

        public MapBuilder withUpdateTime(String ... updateTime) {
            modelProperties.put("updateTime", BaseModel.first(updateTime, getUpdateTime()));
            return this;
        }

        public MapBuilder withUpdateBy(Long ... updateBy) {
            modelProperties.put("updateBy", BaseModel.first(updateBy, getUpdateBy()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}