package com.penglecode.xmodule.platform.upms.model;

import java.util.LinkedHashMap;
import java.util.Map;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import com.penglecode.xmodule.platform.upms.consts.em.UpmsRoleTypeEnum;

/**
 * UPMS角色 (upms_role) 实体类
 * 
 * @author Mybatis-Generator
 * @date	2019年12月24日 下午 17:12:12
 */
@Model(name="UPMS角色", alias="Role")
public class UpmsRole implements BaseModel<UpmsRole> {
     
    private static final long serialVersionUID = 1L;

    /** 角色id */
    @Id
    private Long roleId;

    /** 角色名称 */
    private String roleName;

    /** 角色代码,由字母、下划线组成 */
    private String roleCode;

    /** 角色类型：0-系统角色,1-普通角色 */
    private Integer roleType;

    /** 角色描述 */
    private String description;

    /** 创建时间 */
    private String createTime;

    /** 创建者,用户表的id */
    private Long createBy;

    /** 最近更新时间 */
    private String updateTime;

    /** update_by */
    private Long updateBy;
    
    //以下属于辅助字段
    
    private String roleTypeName;

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleCode() {
        return roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public Integer getRoleType() {
        return roleType;
    }

    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Long getCreateBy() {
        return createBy;
    }

    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public Long getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public String getRoleTypeName() {
		return roleTypeName;
	}

	public void setRoleTypeName(String roleTypeName) {
		this.roleTypeName = roleTypeName;
	}

	@Override
	public UpmsRole decode() {
		if(roleType != null){
			UpmsRoleTypeEnum em = UpmsRoleTypeEnum.getType(roleType);
			if(em != null){
				setRoleTypeName(em.getTypeName());
			}
		}
		return this;
	}
	
	public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            
        }

        public MapBuilder withRoleId(Long ... roleId) {
            modelProperties.put("roleId", BaseModel.first(roleId, getRoleId()));
            return this;
        }

        public MapBuilder withRoleName(String ... roleName) {
            modelProperties.put("roleName", BaseModel.first(roleName, getRoleName()));
            return this;
        }

        public MapBuilder withRoleCode(String ... roleCode) {
            modelProperties.put("roleCode", BaseModel.first(roleCode, getRoleCode()));
            return this;
        }

        public MapBuilder withRoleType(Integer ... roleType) {
            modelProperties.put("roleType", BaseModel.first(roleType, getRoleType()));
            return this;
        }

        public MapBuilder withDescription(String ... description) {
            modelProperties.put("description", BaseModel.first(description, getDescription()));
            return this;
        }

        public MapBuilder withCreateTime(String ... createTime) {
            modelProperties.put("createTime", BaseModel.first(createTime, getCreateTime()));
            return this;
        }

        public MapBuilder withCreateBy(Long ... createBy) {
            modelProperties.put("createBy", BaseModel.first(createBy, getCreateBy()));
            return this;
        }

        public MapBuilder withUpdateTime(String ... updateTime) {
            modelProperties.put("updateTime", BaseModel.first(updateTime, getUpdateTime()));
            return this;
        }

        public MapBuilder withUpdateBy(Long ... updateBy) {
            modelProperties.put("updateBy", BaseModel.first(updateBy, getUpdateBy()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}