package com.penglecode.xmodule.ordercenter.model;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.IdClass;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import com.penglecode.xmodule.ordercenter.model.OrderDetail.PrimaryKey;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 订单明细 (cg_order_detail) 实体类
 * 
 * @author Mybatis-Generator
 * @date	2020年04月22日 上午 10:29:57
 */
@IdClass(PrimaryKey.class)
@Model(name="订单明细", alias="OrderDetail")
public class OrderDetail implements BaseModel<OrderDetail> {
     
    private static final long serialVersionUID = 1L;

    /** 订单ID */
    @Id
    private Long orderId;

    /** 商品ID */
    @Id
    private Long productId;

    /** 商品名称 */
    private String productName;

    /** 购买时的商品详情URL */
    private String productUrl;

    /** 商品单价 */
    private Double unitPrice;

    /** 购买数量 */
    private Integer quantity;

    /** 运费 */
    private Double freightAmount;

    /** 小计 */
    private Double subTotalAmount;

    //以下属于辅助字段

    private Double minUnitPrice;

    private Double maxUnitPrice;

    private Double minSubTotalAmount;

    private Double maxSubTotalAmount;

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductUrl() {
        return productUrl;
    }

    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Double getFreightAmount() {
        return freightAmount;
    }

    public void setFreightAmount(Double freightAmount) {
        this.freightAmount = freightAmount;
    }

    public Double getSubTotalAmount() {
        return subTotalAmount;
    }

    public void setSubTotalAmount(Double subTotalAmount) {
        this.subTotalAmount = subTotalAmount;
    }

    public Double getMinUnitPrice() {
        return minUnitPrice;
    }

    public void setMinUnitPrice(Double minUnitPrice) {
        this.minUnitPrice = minUnitPrice;
    }

    public Double getMaxUnitPrice() {
        return maxUnitPrice;
    }

    public void setMaxUnitPrice(Double maxUnitPrice) {
        this.maxUnitPrice = maxUnitPrice;
    }

    public Double getMinSubTotalAmount() {
        return minSubTotalAmount;
    }

    public void setMinSubTotalAmount(Double minSubTotalAmount) {
        this.minSubTotalAmount = minSubTotalAmount;
    }

    public Double getMaxSubTotalAmount() {
        return maxSubTotalAmount;
    }

    public void setMaxSubTotalAmount(Double maxSubTotalAmount) {
        this.maxSubTotalAmount = maxSubTotalAmount;
    }

    public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    public PrimaryKey ofPrimaryKey() {
        return new PrimaryKey(orderId, productId);
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            super();
        }

        public MapBuilder withOrderId(Long ... orderId) {
            modelProperties.put("orderId", BaseModel.first(orderId, getOrderId()));
            return this;
        }

        public MapBuilder withProductId(Long ... productId) {
            modelProperties.put("productId", BaseModel.first(productId, getProductId()));
            return this;
        }

        public MapBuilder withProductName(String ... productName) {
            modelProperties.put("productName", BaseModel.first(productName, getProductName()));
            return this;
        }

        public MapBuilder withProductUrl(String ... productUrl) {
            modelProperties.put("productUrl", BaseModel.first(productUrl, getProductUrl()));
            return this;
        }

        public MapBuilder withUnitPrice(Double ... unitPrice) {
            modelProperties.put("unitPrice", BaseModel.first(unitPrice, getUnitPrice()));
            return this;
        }

        public MapBuilder withQuantity(Integer ... quantity) {
            modelProperties.put("quantity", BaseModel.first(quantity, getQuantity()));
            return this;
        }

        public MapBuilder withFreightAmount(Double ... freightAmount) {
            modelProperties.put("freightAmount", BaseModel.first(freightAmount, getFreightAmount()));
            return this;
        }

        public MapBuilder withSubTotalAmount(Double ... subTotalAmount) {
            modelProperties.put("subTotalAmount", BaseModel.first(subTotalAmount, getSubTotalAmount()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public static class PrimaryKey implements Serializable {
         
        private static final long serialVersionUID = 1L;

        /** 订单ID */
        private Long orderId;

        /** 商品ID */
        private Long productId;

        public PrimaryKey() {
            super();
        }

        public PrimaryKey(Long orderId, Long productId) {
            super();
            this.orderId = orderId;
            this.productId = productId;
        }

        public Long getOrderId() {
            return orderId;
        }

        public void setOrderId(Long orderId) {
            this.orderId = orderId;
        }

        public Long getProductId() {
            return productId;
        }

        public void setProductId(Long productId) {
            this.productId = productId;
        }
    }
}