package com.penglecode.xmodule.ordercenter.model;

import com.penglecode.xmodule.common.codegen.Id;
import com.penglecode.xmodule.common.codegen.Model;
import com.penglecode.xmodule.common.support.BaseModel;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 订单表
 * 
 * @author Mybatis-Generator
 * @date	2020年08月04日 下午 20:29:02
 */
@Model(name="订单", alias="Order")
public class Order implements BaseModel<Order> {
     
    private static final long serialVersionUID = 1L;

    /** 订单ID */
    @Id
    private Long orderId;

    /** 订单总价 */
    private Double totalAmount;

    /** 运费 */
    private Double freightAmount;

    /** 下单时间 */
    private String orderTime;

    /** 客户ID */
    private Long customerId;

    /** 支付方式：0-在线支付，1-货到付款 */
    private Integer paymentType;

    /** 订单状态：0-待付款，1-待发货，2-待收货 */
    private Integer status;

    /** 订单备注 */
    private String remark;

    //以下属于辅助字段

    private Double minTotalAmount;

    private Double maxTotalAmount;

    private String minOrderTime;

    private String maxOrderTime;

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Double getFreightAmount() {
        return freightAmount;
    }

    public void setFreightAmount(Double freightAmount) {
        this.freightAmount = freightAmount;
    }

    public String getOrderTime() {
        return orderTime;
    }

    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Integer getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Double getMinTotalAmount() {
        return minTotalAmount;
    }

    public void setMinTotalAmount(Double minTotalAmount) {
        this.minTotalAmount = minTotalAmount;
    }

    public Double getMaxTotalAmount() {
        return maxTotalAmount;
    }

    public void setMaxTotalAmount(Double maxTotalAmount) {
        this.maxTotalAmount = maxTotalAmount;
    }

    public String getMinOrderTime() {
        return minOrderTime;
    }

    public void setMinOrderTime(String minOrderTime) {
        this.minOrderTime = minOrderTime;
    }

    public String getMaxOrderTime() {
        return maxOrderTime;
    }

    public void setMaxOrderTime(String maxOrderTime) {
        this.maxOrderTime = maxOrderTime;
    }

    public MapBuilder mapBuilder() {
        return new MapBuilder();
    }

    /**
     * Auto generated by Mybatis Generator
     */
    public class MapBuilder {
         
        private final Map<String, Object> modelProperties = new LinkedHashMap<String,Object>();

        MapBuilder() {
            super();
        }

        public MapBuilder withOrderId(Long ... orderId) {
            modelProperties.put("orderId", BaseModel.first(orderId, getOrderId()));
            return this;
        }

        public MapBuilder withTotalAmount(Double ... totalAmount) {
            modelProperties.put("totalAmount", BaseModel.first(totalAmount, getTotalAmount()));
            return this;
        }

        public MapBuilder withFreightAmount(Double ... freightAmount) {
            modelProperties.put("freightAmount", BaseModel.first(freightAmount, getFreightAmount()));
            return this;
        }

        public MapBuilder withOrderTime(String ... orderTime) {
            modelProperties.put("orderTime", BaseModel.first(orderTime, getOrderTime()));
            return this;
        }

        public MapBuilder withCustomerId(Long ... customerId) {
            modelProperties.put("customerId", BaseModel.first(customerId, getCustomerId()));
            return this;
        }

        public MapBuilder withPaymentType(Integer ... paymentType) {
            modelProperties.put("paymentType", BaseModel.first(paymentType, getPaymentType()));
            return this;
        }

        public MapBuilder withStatus(Integer ... status) {
            modelProperties.put("status", BaseModel.first(status, getStatus()));
            return this;
        }

        public MapBuilder withRemark(String ... remark) {
            modelProperties.put("remark", BaseModel.first(remark, getRemark()));
            return this;
        }

        public Map<String, Object> build() {
            return modelProperties;
        }
    }
}